### PR TITLE
Make it possible to use the plugin sitewide

### PR DESCRIPTION
**Pull request by mic4ael**

### CODE REVIEW

**Comment by RBoelter** [comment]
Hi @mic4ael,
thanks for your PR, but it seems that something is disabling the settings on the journal plugin page.
I think that both should work, the site-wide settings and the journal settings, because sometimes it is possible that different journals in a multi-instance use different SSO providers.

**Comment by mic4ael** [comment]
> Hi @mic4ael,
> thanks for your PR, but it seems that something is disabling the settings on the journal plugin page.
> I think that both should work, the site-wide settings and the journal settings, because sometimes it is possible that different journals in a multi-instance use different SSO providers.

That is how I have designed it for now. I don't allow journal admins to enable the plugin If it has already been configured globally. Maybe we could somehow accomodate for both cases?

**Comment by RBoelter** [comment]
Ah ok, but it can be enabled by journal admins if it is not configured globally? If yes, everything is ok and I need to rewrite my test cases.

**Comment by mic4ael** [comment]
> Ah ok, but it can be enabled by journal admins if it is not configured globally? If yes, everything is ok and I need to rewrite my test cases.

Yeah, if it is not enabled globally then every journal can have it configured separately.

**Comment by RBoelter** [comment]
> > Ah ok, but it can be enabled by journal admins if it is not configured globally? If yes, everything is ok and I need to rewrite my test cases.
> 
> Yeah, if it is not enabled globally then every journal can have it configured separately.

Ok, I tested it, but unfortunately it doesn't seem to work properly. If I go to `Administration -> Site Settings -> Plugins`, I can activate the plugin and configure the settings. But if I deactivate the plugin there and go to `Administration -> Hosted Journals -> <Journal> -> Settings Wizard -> Plugins` or to `<Journal> -> Site -> Plugins`, I can activate the plugin but it is not possible to enter the settings (button is missing).
Another problem is that if only one journal is active in OJS, it is not possible to go to `Administration -> Website Settings -> Plugins` because the Plugins tab appears only if two or more journals are active. Which means that the plugin has to be disabled by default for context = 0 if OJS contains only one journal.

**Comment by mic4ael** [comment]
Thanks for checking, would you like me to fix these issues or you have some time to fix them yourself?

> Ok, I tested it, but unfortunately it doesn't seem to work properly. If I go to Administration -> Site Settings -> Plugins, I can activate the plugin and configure the settings. But if I deactivate the plugin there and go to Administration -> Hosted Journals -> <Journal> -> Settings Wizard -> Plugins or to <Journal> -> Site -> Plugins, I can activate the plugin but it is not possible to enter the settings (button is missing).

That is interesting. Probably there is an issue in the `OpenIDPlugin::getActions` method.

> Another problem is that if only one journal is active in OJS, it is not possible to go to Administration -> Website Settings -> Plugins because the Plugins tab appears only if two or more journals are active. Which means that the plugin has to be disabled by default for context = 0 if OJS contains only one journal.

I guess it should be enough to fix the first issue so that users can enable the plugin in a specific journal?

**Comment by mic4ael** [comment]
Probably it is because of `$this->_globallyEnabled = $this->getSetting(0, 'enabled');` which is only initialized during creation of the Plugin class.

**Comment by RBoelter** [comment]
Here you can see what I mean:
screen-capture

I can fix it, but it will take a while because I have a tight schedule in three other projects at the moment. If you have time to fix it, feel free ;-)

**Comment by mic4ael** [comment]
Ok, fixed the issue in https://github.com/leibniz-psychology/openid/pull/9/

**Pull request merged**
